backend:
  name: git-gateway
  branch: main   # change to "master" if that’s your default branch

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "graphics"
    label: "Graphics Gallery"
    folder: "graphics"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }
